### PR TITLE
fixes: out if index exception when adding feature view

### LINKED ISSUE #5781: [Android] addViewAt: failed to insert view
### Summary

The app crashes when using **Drawer navigation** from the `@react-navigation/drawer` package.

When returning to the **map screen**, all **markers disappear**, and after moving the map, the **app crashes** with an error (either instantly or after some time, depending on the number of markers).

```
addViewAt: failed to insert view [13594] into parent [56] at index 4

index: 4, Size: 0
```

The more markers there are, the faster the crash occurs.

With **Stack navigation**, the app works fine.

```
"@react-navigation/drawer": "7.5.10",
"@react-navigation/native": "7.1.18",
"react-native": "0.81.4",
"react-native-safe-area-context": "5.6.1",
"react-native-screens": "4.17.1",
"react-native-maps": "1.26.17",
```

### Reproducible sample code

```TSX
<MapView
  style={styles.map}
  provider={PROVIDER_GOOGLE}
  initialRegion={{
    latitude: 50.45,
    longitude: 30.51667,
    latitudeDelta: 0.5,
    longitudeDelta: 0.5,
  }}
  onRegionChangeComplete={(region) => loadPlaces(region)}
>
  {places.map((place, index) => (
    <Marker
      key={index}
      coordinate={place}
    />
  ))}
</MapView>
```

### Steps to reproduce

1. Navigate to the Map screen.
2. Navigate to another screen.
3. Return to the Map screen (either by pressing the back button or selecting it from the drawer).
4. Observe that all markers have disappeared.
5. Try to move the map with your fingers.
6. The app crashes with the following error: `addViewAt: failed to insert view`

### Expected result

The app should not crash, and the map should display all markers correctly.

### Actual result

The map does not show markers, and the app crashes after moving the map.

### React Native Maps Version

1.26.17

### What platforms are you seeing the problem on?

Android

### React Native Version

0.81.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung S25

### Additional information

Image

### PR DESCRIPTION
**Pull request by CptFabulouso**
### Does any other open PR do the same thing?

https://github.com/react-native-maps/react-native-maps/pull/5770 possibly tries to address similar issue,  but [fails](https://github.com/react-native-maps/react-native-maps/issues/5750#issuecomment-3388630099). Although my primary focus was to fix https://github.com/react-native-maps/react-native-maps/issues/5781 

### What issue is this PR fixing?

https://github.com/react-native-maps/react-native-maps/issues/5781
Possibly also this https://github.com/react-native-maps/react-native-maps/issues/5750

### How did you test this PR?

I have very similar setup to what the issues above specify, meaning problems after navigating away from the screen with map and navigating back. These changes seem to fix it for my use case.

### PR explanation

When navigatin away from the screen, `onDetachedFromWindow` lifecycle is called, which calls `features.clear()`.
After navigating back to the screen, RN re-mounts the views (I think), and `addView` methods are called (before `onAttachedToWindow`). 
The `addView` may be called first with view at index 1, which ends up with IndexOutOfBoundsException, because `features` ware cleared and we must first add item at index 0.
Only after views are added the `onAttachedToWindow` is called.

So the fix checks whether the component is detached (paused) and if so, saves the component into `savedFeatures` instead and after the `onAttachedToWindow` is called, they get mounted via the existing code there

That's also probably the reason why https://github.com/react-native-maps/react-native-maps/issues/5781#issuecomment-3421142296 works, because I assume that prevents running the `onDetachedFromWindow` lifecycle.

### CODE REVIEW

**Comment by CptFabulouso** [comment]
I've checked that this resolves https://github.com/react-native-maps/react-native-maps/issues/5750 with the provided reproduction repo

**Comment by maXXCZ1** [comment]
> I've checked that this resolves #5750 with the provided reproduction repo

@salah-ghanim I experienced same issue as described here:
https://github.com/react-native-maps/react-native-maps/issues/5781#issuecomment-3427708491

This PR fixes the issue for me.

**Comment by maXXCZ1** [comment]
> > I've checked that this resolves #5750 with the provided reproduction repo
> 
> @salah-ghanim I experienced same issue as described here: [#5781 (comment)](https://github.com/react-native-maps/react-native-maps/issues/5781#issuecomment-3427708491)
> 
> This PR fixes the issue for me.



> > I've checked that this resolves #5750 with the provided reproduction repo
> 
> @salah-ghanim I experienced same issue as described here: [#5781 (comment)](https://github.com/react-native-maps/react-native-maps/issues/5781#issuecomment-3427708491)
> 
> This PR fixes the issue for me.

I am however still experiencing issue with android map markers being rendered in place of original markers.
This issue:
https://github.com/react-native-maps/react-native-maps/issues/5778

@CptFabulouso 
Did you experience this? I am on 1.26.18 with this commit as patch.

//edit I am using clustering, but it even if i disable it. Once i try to re-render markers from another screen, there are basic marker Android icons instead of Those that were detached (filtered out) and they stay visible no matter what (duplicate my markers if i reset filters).

**Comment by CptFabulouso** [comment]
@maXXCZ1 No not in my use case. I'd like to look into it, but not sure if I'll find time for that :/ 
Have you tried turning off detaching inactive screens (I guess it's react-navigation prop?), like mentioned in this issue here https://github.com/react-native-maps/react-native-maps/issues/5781#issuecomment-3421142296?

**Comment by maXXCZ1** [comment]
@CptFabulouso No, i tried but sadly no imprevements. But bug addressed with your PR is in my case solved, thanks.

**Comment by code-strategist** [comment]
this crash happened once on prod with this changes. Not sure how to reproduce it.

```
Exception com.facebook.jni.CppException:
  at com.rnmaps.maps.MapView.safeAddFeature (MapView.java:1162)
  at com.rnmaps.maps.MapView.addFeature (MapView.java:1178)
  at com.rnmaps.fabric.MapViewManager.addView (MapViewManager.java:320)
  at com.rnmaps.fabric.MapViewManager.addView (MapViewManager.java:43)
  at com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt (SurfaceMountingManager.java:407)
  at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute (IntBufferBatchMountItem.kt:122)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue (MountItemDispatcher.kt:325)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems (MountItemDispatcher.kt:231)
  at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems (MountItemDispatcher.kt:89)
  at com.facebook.react.fabric.FabricUIManager$3.runGuarded (FabricUIManager.java:943)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.kt:19)
  at com.facebook.react.fabric.FabricUIManager.scheduleMountItem (FabricUIManager.java:946)
  at com.swmansion.reanimated.NativeProxy.performOperations (NativeProxy.java)
  at com.swmansion.reanimated.NodesManager.performOperations (NodesManager.java:121)
  at com.swmansion.reanimated.NativeProxy.maybeFlushUIUpdatesQueue (NativeProxy.java:491)
  at com.swmansion.worklets.AndroidUIScheduler.triggerUI (AndroidUIScheduler.java)
  at com.swmansion.worklets.AndroidUIScheduler.lambda$new$0 (AndroidUIScheduler.java:27)
  at com.swmansion.worklets.AndroidUIScheduler$1.runGuarded (AndroidUIScheduler.java:49)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.kt:19)
  at android.os.Handler.handleCallback (Handler.java:959)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loopOnce (Looper.java:257)
  at android.os.Looper.loop (Looper.java:342)
  at android.app.ActivityThread.main (ActivityThread.java:9634)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:619)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:929)
  ```

**Comment by tiempham** [comment]
I fixed this issue by remove the map view when navigating away from the screen

**Comment by CptFabulouso** [comment]
@code-strategist Thanks for your feedback. It's hard to tell, but it may be reanimated issue. Part of the error stack trace is similar to the stack trace in this issue https://github.com/software-mansion/react-native-reanimated/issues/4470 
In past I've had troubles with reanimated, just using one of its hooks broke other parts of the app in some ways, even crashed, they fixed a lot of it since.
Are you using latest Reanimated version? Is your MapView wrapped by Reanimated component, or maybe Marker has Reanimated component as a child?

**Comment by code-strategist** [comment]
@CptFabulouso Hi P, yes the map + marker are wrapped with a Reanimated.View. I'm using the version `4.1.3`.
However the `AnimatedMarkerBase ` doesn't have Reanimated in his children.

```ts
const AnimatedMarkerBase = Animated.createAnimatedComponent(
  MapMarker as React.ComponentClass<MarkerProps>,
);
```
Without clear reproducing on my side, it's hard to debug.

**Review by code-strategist — CHANGES_REQUESTED** [review]

**Review by code-strategist — APPROVED** [review]
@salah-ghanim please review, the changes have been been tested.

**Comment by ernstmul** [comment]
I've also confirmed this works. Tagging @GETAWAY-Dev as well (approved more recent PR's)

**Comment by PABourdais** [comment]
Do you guys have an idea on when this fix can be released? I tested on Android 15 and it removed the error.

Thank you for maintaining this package ❤️

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

File: android/src/main/java/com/rnmaps/maps/MapView.java [hunk 1]
```diff
@@ -1156,13 +1160,34 @@ public void setHandlePanDrag(boolean handlePanDrag) {
         this.handlePanDrag = handlePanDrag;
     }
 
+    private void safeAddFeature(int index, MapFeature mapFeature){
+        if(paused || features.size() < index){
```
Comment (tukez) [inline android/src/main/java/com/rnmaps/maps/MapView.java:1164]: features.size() < index check does not quite make sense to me. What does it have to do with savedFeatures?

Comment (CptFabulouso) [reply android/src/main/java/com/rnmaps/maps/MapView.java:1164]: I am not sure what was the initial reason now, but it seems to me like it's not needed anymore after those proposed changes.
